### ISSUE TITLE
Evaluation scripts

### ISSUE THREAD

**Issue by leopauly** [zhang-pengyu/HMFT#10]
Where can we find the scripts to evaluate the predicted results by the pre-trained model ? When the running the prediction scripts (for example run_RGBT210.py), it only generates the predictions of the model on that dataset. No performance metrics are generated.

**Comment by zhang-pengyu** [comment]
The author of RGBT210 seems not provide the evaluation toolkit. I evaluate it by modifying the [RGBT234](https://sites.google.com/view/ahutracking001/) toolkit. I modified the MSR to SR, since RGBT210 only provides a single GT file.

**Comment by leopauly** [comment]
Thanks for the reply. So did you use the same evaluation script of [RGBT234 ](https://sites.google.com/view/ahutracking001/) for evaluating the predictions from VTUAV (run_VTUAV.py) and GTOT (run_GTOT.py) dataset sets as well?

Can you please upload the modified eval scripts you used to the repository?

**Comment by zhang-pengyu** [comment]
No, both VTUAV and GTOT has their own evaluation toolkit. you can refer to [VTUAV](https://github.com/zhang-pengyu/DUT-VTUAV) and [GTOT](http://chenglongli.cn/code-dataset/) for more details
