### ISSUE TITLE
关于提供的结果

### ISSUE THREAD

**Issue by pkqpotter123** [zhang-pengyu/HMFT#11]
![63a9dff249f61f7e8a4c6d7247ba916](https://user-images.githubusercontent.com/117645500/233064829-4c0a2fd2-ab9c-49bf-8ab5-84b9dc982bf8.png)
您好，请问图片下方链接提供的追踪结果和表格中的指标一致吗，我用VTUAV数据集的toolkit在链接中的结果上运行，得到的指标和表格给出的62.7，75.8差别比较大

**Comment by zhang-pengyu** [comment]
提供的跟踪结果和表格一致，你可以按照[link](https://github.com/zhang-pengyu/DUT-VTUAV#how-to-evaluate)的评估方式看下步骤是否有问题

**Comment by pkqpotter123** [comment]
感谢作者的回答
