### ISSUE TITLE
In which directory should the downloaded pre-trained model be placed?

### ISSUE THREAD

**Issue by 981410121** [zhang-pengyu/HMFT#18]
In which directory should the downloaded pre-trained model be placed?

**Comment by zhang-pengyu** [comment]
Following mfDiMP/pytracking/evaluation/environment.py , you need to put the network at mfDiMP/networks.

**Comment by 981410121** [comment]
> 根据 mfDiMP/pytracking/evaluation/environment.py ，您需要将网络放在 mfDiMP/networks 。
Thanks a lot, I will close this question
