### ISSUE TITLE
师兄，能提供init_frame.npy这个文件吗

### ISSUE THREAD

**Issue by dudongli** [zhang-pengyu/HMFT#2]

**Comment by zhang-pengyu** [comment]
你好，抱歉缺失了文件，用于训练VTUAV的文件（init_frame.npy, ST_train.txt, ST_val.txt, LT_train.txt, LT_val.txt）已经上传，你可以在[这里](https://github.com/zhang-pengyu/HMFT/tree/master/mfDiMP)找到

**Comment by NewboySoCool** [comment]
> 你好，抱歉缺失了文件，用于训练VTUAV的文件（init_frame.npy, ST_train.txt, ST_val.txt, LT_train.txt, LT_val.txt）已经上传，你可以在[这里](https://github.com/zhang-pengyu/HMFT/tree/master/mfDiMP)找到

good
