### ISSUE TITLE
关于数据集和训练代码

### ISSUE THREAD

**Issue by yangjiangeyjg** [zhang-pengyu/HMFT#3]
您好，请问您们会开源训练代码嘛，谢谢！

**Comment by zhang-pengyu** [comment]
你好，训练代码已开源（详见$root/mfDiMP/ltr/run_training.py）,数据集已公开（https://github.com/zhang-pengyu/DUT-VTUAV）

**Comment by yingchoudiejuan** [comment]
在您的代码里，看见了gotk10k数据集，您有尝试将其转换为红外模态，变成RGBT跟踪数据集，请问您是用什么方法转换的？将got10k转换为RGBT跟踪数据集，对模型训练有帮助吗？

**Comment by zhang-pengyu** [comment]
我们的算法在训练过程中没有用到GOT10k，有关使用生成样本训练RGBT跟踪器的工作可以看看mfDiMP和[LSS-dataset](https://github.com/RaymondCover/LSS-Dataset)
