### ISSUE TITLE
AttributeError: 'Tracker' object has no attribute 'parameters'

### ISSUE THREAD

**Issue by MUHAMMEDZEYN** [zhang-pengyu/HMFT#5]
Hello,
When I tried to run demo.py I had the folowwing error: 

```
Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    tracker.parameters.features.features[0].dis_net_path = 'OptimTracker_ep'+str(45).zfill(4)+'.pth.tar'
AttributeError: 'Tracker' object has no attribute 'parameters'
```

I believe that the conda environment is created and all the mecessary packages have installed succusfully. Any advice would be useful for me. 
Thanks in advance

**Comment by zhang-pengyu** [comment]
I have checked the code and run it correctly. Please check the pytorch version(1.2.0) and install the packages using install.sh
