### ISSUE TITLE
about Long-term tracking

### ISSUE THREAD

**Issue by 972821054** [zhang-pengyu/HMFT#6]
Hello, thank you very much for the dataset and benchmark code you provided. I have a question to ask you. How do you deal with the frames where the objects disappear after the objects disappear in the image during the training phase? I would be very grateful if you could get back to me!

**Comment by zhang-pengyu** [comment]
Thank for attention. The out-of-view frames will be removed in training phase according to the ground truth.

**Comment by 972821054** [comment]
@zhang-pengyu thank you very much
