### ISSUE TITLE
Links to the demos not working 

### ISSUE THREAD

**Issue by leopauly** [zhang-pengyu/HMFT#8]
The following links to download demos seems to be broken:

https://drive.google.com/uc?id=1LeYyYxPA5XBF4m73T1p9qXsmGKVV7Fmm
https://drive.google.com/uc?id=1yrtTYKcUfNsk-jxjXmY54FIxtBS3Fz9H 
https://drive.google.com/uc?id=1uiqFuG3RnWcyu-OaRzKIQhrCLXKKM7_z 
https://drive.google.com/uc?id=1fL4Yo4xBSndeE_ShAqrraiHAL7QvrEAi 

**Error message:**

         $ gdown https://drive.google.com/uc?id=1LeYyYxPA5XBF4m73T1p9qXsmGKVV7Fmm -O mfDiMP/demo/bus1.zip

         Access denied with the following error:
       
         Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

         You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1LeYyYxPA5XBF4m73T1p9qXsmGKVV7Fmm

**Comment by zhang-pengyu** [comment]
Thanks for your reminder. The samples are from the proposed VTUAV dataset. You can directly evaluate on it or run the provided [demo](https://github.com/zhang-pengyu/HMFT/tree/master/mfDiMP/demo/bus1_sample).

**Comment by leopauly** [comment]
thanks for the reply. I will close the issue then.
