### ISSUE TITLE
 Cuda Error : RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by leopauly** [zhang-pengyu/HMFT#9]
While trying to run the demo.py, we get the following error:

            Cuda Error : RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

Looks like there is an mismatch in the cuDNN version to be installed. Can you provide the cuDNN version which was used to train the model 'OptimTracker_ep0045.pth.tar' ?

**Comment by zhang-pengyu** [comment]
The tracker is run with cuda 10.0 pytorch 1.2. You should install the environment with the guidance of [install.sh](https://github.com/zhang-pengyu/HMFT/blob/master/install.sh)

**Comment by leopauly** [comment]
Thanks for the quick response. Closing the issue now.
